### ISSUE TITLE
Improvements to owlzoom add-on firefox

### ISSUE THREAD

**Issue by crawkn** [LionRoar/WebExt-OwlZoom#1]
This is a useful add-on, thank you.

Most commonly one would want to zoom to the center of the image (where the action is), so I would recommend making this the default start position.

Also, the movement (scaling, in your language) within the image is very slow, so please increase the speed of panning across the video.

**Comment by LionRoar** [comment]
Thanks for support , i will consider your requests for the next update
 stay tuned
