### ISSUE TITLE
Port to Chrome Extension?

### ISSUE THREAD

**Issue by lflee** [LionRoar/WebExt-OwlZoom#2]
Thanks man, the add-on works as advertised.

Just wondering if you are considering porting it to Chrome?
Or there's already a solution to zoom on viewers commands on Chrome?

Nice day~

**Comment by LionRoar** [comment]
first of all Thank you! for your review and sorry for late reply ,
Actually this Extension works well both on Firefox and Chrome but i did not post it on the chrome ext store yet but hopefully i will very soon , till then you could use it on chrome just download the files and follow this steps for chrome: 
https://developer.chrome.com/extensions/getstarted#unpacked
notes that there's new version with a lot of improvements on Scale and Move around the video  *under file 'v2'
and Thank you again and have a nice day :)

**Comment by lflee** [comment]
Thanks, and in the meantime, I discovered [Turn Off the Lights](https://chrome.google.com/webstore/detail/turn-off-the-lights/bfbmjmiodbnnpllbbbfblcplfjjepjdn?hl=en). It's zooming is good too.
